[package]
name = "merge-workflow"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
common-models = { path = "../common-models" }
serde = { version = "1.0", features = ["derive"] }
utils = { path = "../utils" }

clients = { path = "../clients" }
conversation = { path = "../conversation" }
interaction = { path = "../interaction" }
response-stream = { path = "../response-stream" }
tools = { path = "../tools" }
turn-engine = { path = "../turn-engine" }
workspace-access = { path = "../workspace-access" }
futures = "0.3"
serde_json = "1.0"
tokio = { version = "1", features = ["rt", "time"] }

[dev-dependencies]
serde_json = "1.0"
