[package]
name = "merge-workflow"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
common-models = { path = "../common-models" }
serde = { version = "1.0", features = ["derive"] }
utils = { path = "../utils" }

clients = { path = "../clients" }
interaction = { path = "../interaction" }
tools = { path = "../tools" }
turn-engine = { path = "../turn-engine" }
workspace-access = { path = "../workspace-access" }
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
serde_json = "1.0"
