[package]
name = "turbo-code"
version = "0.1.0"
edition = "2024"


[dependencies]
ra_ap_load-cargo = "0.0.300"
ra_ap_project_model = "0.0.300"
ra_ap_ide = "0.0.300"
ra_ap_ide_db = "0.0.300"
ra_ap_hir = "0.0.300"
ra_ap_syntax = "0.0.300"
ra_ap_vfs = "0.0.300"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
thiserror = "1.0"
async-stream = "0.3.6"
futures = "0.3"
bytes = "1.0"
url = "2.4"
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0.99"
ractor = "0.15"
simplelog = "^0.12.0"
log = "0.4.27"