[package]
name = "turbo-code"
version = "0.1.0"
edition = "2024"


[dependencies]
reqwest = { version = "0.12.25", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
thiserror = "2.0.17"
async-stream = "0.3.6"
futures = "0.3"
ractor_actors = "0.4.9"
ra_ap_ide = "0.0.311"
ra_ap_load-cargo = "0.0.311"
ra_ap_project_model = "0.0.311"
ra_ap_ide_db = "0.0.311"
ra_ap_vfs = "0.0.311"
ra_ap_hir = "0.0.311"
ra_ap_syntax = "0.0.311"
bytes = "1.0"
url = "2.4"
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0.99"
ractor = "0.15"
simplelog = "^0.12.0"
log = "0.4.27"
color-eyre = "0.6.5"
ratatui = "0.30.0-beta.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
heed = "0.22.0"
textwrap = "0.16"
tui = "0.19.0"
cargo_metadata = "0.18"
itertools = "0.14.0"