[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
grep = "0.4.1"
cargo_metadata = "0.23.1"
anyhow = "1.0.99"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
tokio-stream = { version = "0.1", features = ["fs", "io-util"] }
futures = "0.3"
blake3 = "1.8.3"
uuid = { version = "1.0", features = ["v4", "serde"] }
dirs = "6.0.0"
itertools = "0.15.0"
fnv = "1.0.7"
tokio-util = { version = "0.7", features = ["rt"] }
libc = "0.2"

[target.'cfg(unix)'.dependencies]
rustix = { version = "1.1.4", features = ["fs"] }
