[package]
name = "analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
anyhow = "1.0.99"
ra_ap_ide = "0.0.311"
ra_ap_load-cargo = "0.0.311"
ra_ap_project_model = "0.0.311"
ra_ap_ide_db = "0.0.311"
ra_ap_vfs = "0.0.311"
ra_ap_hir = "0.0.311"
ra_ap_syntax = "0.0.311"
itertools = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
futures = "0.3"
heed = "0.22.0"
tokio = { version = "1.0", features = ["full"] }
turbo-code-macros = { path = "../turbo-code-macros" }
blake3 = "1.8.3"
triomphe = "0.1.15"
async-trait = "0.1.89"
